apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-toolkit
  region: us-west-2
  version: "1.21"
managedNodeGroups:
- instanceType: m5.large
  amiFamily: AmazonLinux2
  name: devops-toolkit
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
iam:
  withOIDC: true
