apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values: [us-west-2a] # Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-devops-toolkit
  ttlSecondsAfterEmpty: 30
